Sprint 1
Raketich/middle.messenger.praktikum.yandex pull request #1
Opened 2022-11-04 19:35 UTC by Raketich

Настройка проекта: parcel, handlebars, express. Верстка основных страниц без придания финального вида по макету.
Для удобства переключения между экранами используется функция, которая в зависимости от pathname монтирует нужную страницу.

2022-11-05 23:20 UTC, agadoev requested changes
Привет, @Raketich 
Добавь, пожалуйста, в .gitignore следующие строки
```
.parchel-cache
.node_modules
dist
build
```
и отправь на повторное ревью.
Сейчас в реквесте 5000+ изменений + кажется, что нет изменений исходников

2022-11-07 00:25 UTC, agadoev approved these changes
Привет, @Raketich 
спасибо за работу
В целом все ок, я заметил незначительные правки, работа принимается
Удачи в следующих спринтах :)

2022-11-07 00:25 UTC, agadoev commented on src/components/avatar/styles.css
> +    color: #559fce;
цвета нужно вынести в отдельный файл и хранить в виде переменной

2022-11-07 00:25 UTC, agadoev commented on server.js
> +const PORT = 3000;
бывает очень полезно задавать порт в переменных окружения (когда будешь докер настраивать), поэтому тут лучше написать так
```suggestion
const PORT = process.env.PORT || 3000;
```

2022-11-07 00:25 UTC, agadoev commented on src/components/avatar/avatar.hbs
> +    <p>A</p>
кажется, что в компоненте ```avatar```,  должен быть тег ```img```

2022-11-07 00:25 UTC, agadoev commented on src/components/input/input.hbs
> +<label for="{{name}}">
я думаю, сюда еще стоит добавить текст для ```label```

2022-11-11 21:39 UTC, Raketich commented on src/components/input/input.hbs
> +<label for="{{name}}">
label здесь для доступности. Наверное, можно оставить без текста?

2022-11-11 21:43 UTC, Raketich commented on src/components/avatar/avatar.hbs
> +    <p>A</p>
Поправил в ветке второго спринта

2022-11-11 21:56 UTC, Raketich commented on src/components/avatar/styles.css
> +    color: #559fce;
переменные завел, надо пройтись по проекты и заменить везде

2022-11-11 21:57 UTC, merged